### PR TITLE
adding in some basic shortcuts to ace for bold and italic

### PR DESCRIPTION
**Pull request by jcblw**

### CODE REVIEW

**Comment by jcblw** [comment]
just a start but its good we now have a clear way to add shortcuts

**Comment by itsjustmath** [comment]
@jcblw I pulled down your new changes and get an error when I try to run a new build. Can you provide some more in depth directions in the readme on NPM/NVM setup for pastila?

**Comment by jcblw** [comment]
screen shot 2015-11-19 at 8 21 44 am

This should be the extent of it, are you having issues with node 4+? @itsjustmath

**Comment by itsjustmath** [comment]
I haven't changed anything @jcblw - pulled down and ran `npm install` + `npm run build`, got this:

``` bash
 pastila@1.1.2 build /Users/itsjustmath/Projects/pastila
> npm run styles && rm -rf Pastila.app && electron-packager app/ Pastila --icon=assets/icon.icns


> pastila@1.1.2 styles /Users/itsjustmath/Projects/pastila
> node scripts/styles.js app/client/styles/main.css app/client/app.css


/Users/itsjustmath/Projects/pastila/scripts/styles.js:3
const cssnext = require('cssnext')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

npm ERR! pastila@1.1.2 styles: `node scripts/styles.js app/client/styles/main.css app/client/app.css`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the pastila@1.1.2 styles script.
npm ERR! This is most likely a problem with the pastila package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/styles.js app/client/styles/main.css app/client/app.css
npm ERR! You can get their info via:
npm ERR!     npm owner ls pastila
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 15.0.0
npm ERR! command "/Users/itsjustmath/.nvm/v0.10.36/bin/node" "/Users/itsjustmath/.nvm/v0.10.36/bin/npm" "run" "styles"
npm ERR! cwd /Users/itsjustmath/Projects/pastila
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/itsjustmath/Projects/pastila/npm-debug.log
npm ERR! not ok code 0

npm ERR! pastila@1.1.2 build: `npm run styles && rm -rf Pastila.app && electron-packager app/ Pastila --icon=assets/icon.icns`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pastila@1.1.2 build script.
npm ERR! This is most likely a problem with the pastila package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run styles && rm -rf Pastila.app && electron-packager app/ Pastila --icon=assets/icon.icns
npm ERR! You can get their info via:
npm ERR!     npm owner ls pastila
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 15.0.0
npm ERR! command "/Users/itsjustmath/.nvm/v0.10.36/bin/node" "/Users/itsjustmath/.nvm/v0.10.36/bin/npm" "run" "build"
npm ERR! cwd /Users/itsjustmath/Projects/pastila
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/itsjustmath/Projects/pastila/npm-debug.log
npm ERR! not ok code 0
```

**Comment by jcblw** [comment]
screen shot 2015-11-19 at 8 53 11 am

you using node `0.10.36`

`nvm use 4`

**Pull request merged**
