### PR TITLE
Responsive visual enhancements + menu style fixes

### LINKED ISSUE #32: Menu styles broken
So with the latest merge some of the menu styles we kinda busted.

screen shot 2015-06-07 at 10 08 35 am
screen shot 2015-06-07 at 10 08 43 am

### PR DESCRIPTION
**Pull request by itsjustmath**
- fixes #32 
- font size scales slightly as the viewport shrinks
- workspace now maxes out at 80 characters width, put remains centered as the viewport expands in width

### CODE REVIEW

**Comment by jcblw** [comment]
im still seeing the clipping happening on the menu is this just addressing the size in #32

**Comment by itsjustmath** [comment]
I think it's still gonna clip if your viewport height is too small

**Comment by itsjustmath** [comment]
So yeah it's adjusting the issue with the modal heights

**Comment by jcblw** [comment]
Hmmmm, i dont think its my viewport height it has to do with padding on the bottom of the modal.

**Comment by itsjustmath** [comment]
is this what youre talking about?

**Comment by jcblw** [comment]
No, checkout the file list its pretty much always cropping. n matter what the breakpoint is.

**Pull request merged**
