### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by itsjustmath**
Resolves line height issue in #19. @jcblw let me know what you think about my solution making the deletion icon less prominent (I gave it a lower opacity).

Hold off on merging this into master yet, theres this weird bug that I'm running across where I can't click or select text on any headers, anything starting with `#`

### CODE REVIEW

**Comment by jcblw** [comment]
is this still having that same issue with the header stuff?

**Comment by itsjustmath** [comment]
yeah unfortunately it still is

**Comment by jcblw** [comment]
@itsjustmath so figured out the issue, it was more of that the entire editor grid was off 20 px due to a new style switched it up to a place that will not effect the grid but also addes the top padding.

**Comment by itsjustmath** [comment]
good catch :+1:

**Pull request merged**
